### PR TITLE
rename modules folders

### PR DESCRIPTION
**Pull request by loki666**
how about this one?

### CODE REVIEW

**Comment by loki666** [comment]
it seems git is mixing moves from modules folders, but that's ok because they have the same content

**Comment by loki666** [comment]
I can split the commit, for each module, if you want?

**Comment by philburk** [comment]
This looks good. The key this is that the diff says "File renamed without changes." Then we don't have to study this commit to see if something broke due to an inadvertent change.

**Comment by philburk** [comment]
The links on this page work again. Thanks!
https://source.android.com/devices/audio/midi_test.html

**Pull request merged**
